all:
  children:
    wiki:
      hosts:
        my_host:
          ansible_host: 8.8.8.8 
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_rsa # path to your ssh-key